spring:
  output:
    ansi:
      enabled: always
server:
  address: 127.0.0.1
  port: 8080
  http2:
    enabled: true
management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: "*"
